### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by makintoshi** [idvogados/idvogados.github.io#3]
# CONTEXTO/PROPÓSITO
Todo produto precisa de uma página principal (homepage).

Ela será o primeiro contato do produto com seus interessados: 
- usuários (entregadores / advogados)
- profissionais que querem ajudar com o desenvolvimento
- pessoas que querem acompanhar o andamento 
- contribuintes

O propósito aqui é criar página que servirá como ponto de partida para todas essas pessoas levando em consideração os critérios de aceite abaixo:

# CRITÉRIOS DE ACEITE
1) Deve ser simples e leve (algumas pessoas podem ter internet ruim)
2) Deve explicar qual é a proposta do projeto
3) Deve explicar como funciona (explicitando o anonimato dos entregadores e a atividade pró-bono dos advogados)
4) Deve explicar a motivação do projeto/como ele surgiu (vídeo curto do Greg News)
5) Deve ser o ponto de partida para todas as pessoas:
5.1) Se for entregador/advogado, ao clicar no botão referente ao seu perfil, abriremos o Google Forms correspondente a ele (teremos um pra cada)
5.2) Se for alguém querendo contribuir com o projeto (voluntário, contribuinte), deve haver um botão (ex: "Quero colaborar" que abrirá a página de contribuição (falaremos sobre ela em outra issue)
6) Deve oferecer conteúdo para que os entregadores se informem mais sobre o assunto
7) Deve ter a política de privacidade e os termos de uso
8) Deve permitir o compartilhamento p/ redes sociais e WhatsApp

**Comment by ricardoquecria** [comment]
Vou fazer um esboço aqui.

**Comment by IsabelElia** [comment]
https://projects.invisionapp.com/d/#/console/19856583/415511916/comments
segue um wire-frame com sugestão de Homepage para esta issue :)

**Comment by rodrigondec** [comment]
> https://projects.invisionapp.com/d/#/console/19856583/415511916/comments
> segue um wire-frame com sugestão de Homepage para esta issue :)

@IsabelElia Tem como compartilhar para pessoas sem conta ver? Ou é obrigatório ter conta?

**Comment by IsabelElia** [comment]
https://invis.io/JDX2C095RQS#/415511916_Web_1920_-_2
veja se agora vai. Senao, vc ta nos chats do discord? Posso te passar as img por la tb.

**Comment by caike08** [comment]
Como está o desenvolvimento da homepage? Já tem alguém codando? Precisam de alguma ajuda?

**Comment by rodrigondec** [comment]
> Como está o desenvolvimento da homepage? Já tem alguém codando? Precisam de alguma ajuda?

Não há ninguem codando ainda. Estamos fazendo um fluxo orientado à issues/tarefas. 
Assim que conseguirmos organizar a criar tarefas para codar mesmo aceitaremos PR's para tal.

**Comment by pictos** [comment]
@IsabelElia, esse wireframe é a versão final da UI? Pergunto isso para preparar os tickets para o time de front.

**Comment by mm44m6** [comment]
A homepage foi concluída, será disponibilizada em uma conta Netlify do idvogados.
