### ISSUE TITLE
[Bug] 'typo' nos Termos de Uso (Colaboradores)

### ISSUE THREAD

**Issue by andrebts** [idvogados/idvogados.github.io#8]
### Descrição problema

Na página dos [Termos de Uso (Colaboradores)] na seção "4. Dos materiais produzidos" item 3, está escrito "[...] pertença **ao** você mesmo ou se **ele** tiver a permissão do proprietário para divulgá-las [...]" onde o termo "ao" deveria ser "a" e o pronome "ele" deveria ser removido. Com essas correções o trecho ficaria "[...] pertença a você mesmo ou se tiver a permissão do proprietário para divulgá-las".

### Passos para reproduzir

1. Acessar Docs/Termos de Uso (Colaboradores).md;
2. Navegar até a seção "4. Dos materiais produzidos";
3. Ler o item 3.

### Reproduction Link
https://github.com/idvogados/idvogados.github.io/blob/master/Docs/Termos%20de%20Uso%20(Colaboradores).md#4-dos-materiais-produzidos

**Comment by rodrigondec** [comment]
O documento de termos de uso foi movido para outro repositório.
